# # Versi Docker Compose yang digunakan (yang terkini)
# version: '3.8'

# Jadi dibawah ini kita mendefinisikan semua kotak agar terorkestrasi (kontainer) 
services:
  
  # 1. Kontainer untuk database MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'book_db'  # Nama database Anda
      MYSQL_ROOT_PASSWORD: 'your_strong_password' # password database
    ports:
      # Hubungkan port 3306 di dalam kontainer ke 3307 di komputer Anda
      # (Gunakan 3307 agar tidak bentrok dengan XAMPP)
      - "3307:3306"
    volumes:
      # Simpan data MySQL secara permanen di folder 'mysql-data'
      - ./mysql-data:/var/lib/mysql

  # 2. Kontainer untuk phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: unless-stopped
    ports:
      # Kita bisa buka phpMyAdmin versi Docker di http://localhost:8081
      - "8081:80"
    environment:
      PMA_HOST: db # fungsinya untuk enghubungkan phpMyAdmin ke kontainer db
    depends_on:
      - db # Disini kita harus pastikan db berjalan terlebih dahulu

  # 3. Kontainer untuk Backend Node.js
  backend:
    build: ./server # Bangun dari Dockerfile di folder server
    container_name: backend_api
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      DB_HOST: 'db' # Jadi Backend sudah terhubung ke db bukan lagi ke localhost (tidak perlu lagi membuka XAMPP untuk menjalankan databasenya)
      DB_USER: 'root'
      DB_PASSWORD: 'your_strong_password'
      DB_NAME: 'book_db'
    depends_on:
      - db

  # 4. Kontainer untuk Frontend React
  frontend:
    build: ./client # Bangun dari Dockerfile di folder client
    container_name: react_ui
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend